In [ ]:
!pip install sqlite3

In [2]:
import sqlite3

conn = sqlite3.connect('emaildbb.sqlite')
cur = conn.cursor()

cur.execute('DROP TABLE IF EXISTS Counts')

cur.execute('''
CREATE TABLE Counts (org TEXT, count INTEGER)''')

fname = 'mbox.txt'
if (len(fname) < 1): fname = 'mbox.txt'
fh = open(fname)
for line in fh:
    if not line.startswith('From: '): continue
    pieces = line.split()
    email = pieces[1]
    parts=email.split('@')
    org=parts[1]
    cur.execute('SELECT count FROM Counts WHERE org = ? ', (org,))
    row = cur.fetchone()
    if row is None:
        cur.execute('''INSERT INTO Counts (org, count)
                VALUES (?, 1)''', (org,))
    else:
        cur.execute('UPDATE Counts SET count = count + 1 WHERE org = ?',
                    (org,))
    conn.commit()

# https://www.sqlite.org/lang_select.html
sqlstr = 'SELECT org, count FROM Counts ORDER BY count DESC LIMIT 10'

for row in cur.execute(sqlstr):
    print(str(row[0]), row[1])

cur.close()

iupui.edu 536
umich.edu 491
indiana.edu 178
caret.cam.ac.uk 157
vt.edu 110
uct.ac.za 96
media.berkeley.edu 56
ufp.pt 28
gmail.com 25
et.gatech.edu 17

In [9]:
import sqlite3

conn = sqlite3.connect('itunes.sqlite')
cur = conn.cursor()

cur.execute('DROP TABLE IF EXISTS Counts')

cur.close()

In [3]:
import xml.etree.ElementTree as ET
import sqlite3

conn = sqlite3.connect('trackdb.sqlite')
cur = conn.cursor()

# Make some fresh tables using executescript()
cur.executescript('''
DROP TABLE IF EXISTS Artist;
DROP TABLE IF EXISTS Album;
DROP TABLE IF EXISTS Track;

CREATE TABLE Artist (
    id  INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
    name    TEXT UNIQUE
);

CREATE TABLE Genre (
    id  INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
    name    TEXT UNIQUE
);

CREATE TABLE Album (
    id  INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
    artist_id  INTEGER,
    title   TEXT UNIQUE
);

CREATE TABLE Track (
    id  INTEGER NOT NULL PRIMARY KEY 
        AUTOINCREMENT UNIQUE,
    title TEXT  UNIQUE,
    album_id  INTEGER,
    genre_id  INTEGER,
    len INTEGER, rating INTEGER, count INTEGER
);
''')


fname = "Library.xml"
if ( len(fname) < 1 ) : fname = 'Library.xml'

# <key>Track ID</key><integer>369</integer>
# <key>Name</key><string>Another One Bites The Dust</string>
# <key>Artist</key><string>Queen</string>
def lookup(d, key):
    found = False
    for child in d:
        if found : return child.text
        if child.tag == 'key' and child.text == key :
            found = True
    return None

stuff = ET.parse(fname)
all = stuff.findall('dict/dict/dict')
print('Dict count:', len(all))
for entry in all:
    if ( lookup(entry, 'Track ID') is None ) : continue

    name = lookup(entry, 'Name')
    artist = lookup(entry, 'Artist')
    album = lookup(entry, 'Album')
    genre=lookup(entry,'Genre')
    count = lookup(entry, 'Play Count')
    rating = lookup(entry, 'Rating')
    length = lookup(entry, 'Total Time')

    if name is None or artist is None or album is None or genre is None : 
        continue

#     print(name, artist, album,genre, count, rating, length)

    cur.execute('''INSERT OR IGNORE INTO Artist (name) 
        VALUES ( ? )''', ( artist, ) )
    cur.execute('SELECT id FROM Artist WHERE name = ? ', (artist, ))
    artist_id = cur.fetchone()[0]
    
    cur.execute('''INSERT OR IGNORE INTO Genre (name) 
        VALUES ( ? )''', ( genre, ) )
    cur.execute('SELECT id FROM Genre WHERE name = ? ', (genre, ))
    genre_id = cur.fetchone()[0]
    
    cur.execute('''INSERT OR IGNORE INTO Album (title, artist_id) 
        VALUES ( ?, ? )''', ( album, artist_id ) )
    cur.execute('SELECT id FROM Album WHERE title = ? ', (album, ))
    album_id = cur.fetchone()[0]

    cur.execute('''INSERT OR REPLACE INTO Track
        (title, album_id,genre_id, len, rating, count) 
        VALUES ( ?, ?,?, ?, ?, ? )''', 
        ( name, album_id,genre_id, length, rating, count ) )

    conn.commit()
sqlstr='SELECT Track.title, Artist.name, Album.title,Genre.name FROM Track JOIN Genre JOIN Album JOIN Artist ON Track.genre_id=Genre.ID and Track.album_id=Album.id AND Album.artist_id=Artist.id ORDER BY Artist.name LIMIT 3'

for row in cur.execute(sqlstr):
    print(str(row[0]),str(row[1]),str(row[2]),str(row[3]))
cur.close()

Dict count: 404
For Those About To Rock (We Salute You) AC/DC Who Made Who Rock
Hells Bells AC/DC Who Made Who Rock
Shake Your Foundations AC/DC Who Made Who Rock

In [9]:
import json
import sqlite3

conn = sqlite3.connect('rosterdb.sqlite')
cur = conn.cursor()

# Do some setup
cur.executescript('''
DROP TABLE IF EXISTS User;
DROP TABLE IF EXISTS Member;
DROP TABLE IF EXISTS Course;

CREATE TABLE User (
    id     INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
    name   TEXT UNIQUE
);

CREATE TABLE Course (
    id     INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
    title  TEXT UNIQUE
);

CREATE TABLE Member (
    user_id     INTEGER,
    course_id   INTEGER,
    role        INTEGER,
    PRIMARY KEY (user_id, course_id)
)
''')

fname = "roster_data.json"
if len(fname) < 1:
    fname = 'roster_data.json'

# [
#   [ "Charley", "si110", 1 ],
#   [ "Mea", "si110", 0 ],

str_data = open(fname).read()
json_data = json.loads(str_data)

for entry in json_data:

    name = entry[0];
    title = entry[1];
    role=entry[2];

#     print((name, title,role))

    cur.execute('''INSERT OR IGNORE INTO User (name)
        VALUES ( ? )''', ( name, ) )
    cur.execute('SELECT id FROM User WHERE name = ? ', (name, ))
    user_id = cur.fetchone()[0]

    cur.execute('''INSERT OR IGNORE INTO Course (title)
        VALUES ( ? )''', ( title, ) )
    cur.execute('SELECT id FROM Course WHERE title = ? ', (title, ))
    course_id = cur.fetchone()[0]

    cur.execute('''INSERT OR REPLACE INTO Member
        (user_id, course_id,role) VALUES ( ?, ?, ? )''',
        ( user_id, course_id,role ) )

    conn.commit()
    
test="""SELECT hex(User.name || Course.title || Member.role ) AS X FROM 
    User JOIN Member JOIN Course 
    ON User.id = Member.user_id AND Member.course_id = Course.id
    ORDER BY X"""
cur.execute(test)
result=cur.fetchone()
print(result)
cur.close()
conn.close()

('416262656761696C736934333030',)

In [11]:
import urllib.request, urllib.parse, urllib.error
import http
import sqlite3
import json
import time
import ssl
import sys

api_key = False
# If you have a Google Places API key, enter it here
# api_key = 'AIzaSy___IDByT70'

if api_key is False:
    api_key = 42
    serviceurl = "http://py4e-data.dr-chuck.net/json?"
else :
    serviceurl = "https://maps.googleapis.com/maps/api/geocode/json?"

# Additional detail for urllib
# http.client.HTTPConnection.debuglevel = 1

conn = sqlite3.connect('geodata.sqlite')
cur = conn.cursor()

cur.execute('''
CREATE TABLE IF NOT EXISTS Locations (address TEXT, geodata TEXT)''')

# Ignore SSL certificate errors
ctx = ssl.create_default_context()
ctx.check_hostname = False
ctx.verify_mode = ssl.CERT_NONE

fh = open("where.data")
count = 0
for line in fh:
    if count > 200 :
        print('Retrieved 200 locations, restart to retrieve more')
        break

    address = line.strip()
    print('')
    cur.execute("SELECT geodata FROM Locations WHERE address= ?",
        (memoryview(address.encode()), ))

    try:
        data = cur.fetchone()[0]
        print("Found in database ",address)
        continue
    except:
        pass

    parms = dict()
    parms["address"] = address
    if api_key is not False: parms['key'] = api_key
    url = serviceurl + urllib.parse.urlencode(parms)

    print('Retrieving', url)
    uh = urllib.request.urlopen(url, context=ctx)
    data = uh.read().decode()
    print('Retrieved', len(data), 'characters', data[:20].replace('\n', ' '))
    count = count + 1

    try:
        js = json.loads(data)
    except:
        print(data)  # We print in case unicode causes an error
        continue

    if 'status' not in js or (js['status'] != 'OK' and js['status'] != 'ZERO_RESULTS') :
        print('==== Failure To Retrieve ====')
        print(data)
        break

    cur.execute('''INSERT INTO Locations (address, geodata)
            VALUES ( ?, ? )''', (memoryview(address.encode()), memoryview(data.encode()) ) )
    conn.commit()
    if count % 10 == 0 :
        print('Pausing for a bit...')
        time.sleep(5)

print("Run geodump.py to read the data from the database so you can vizualize it on a map.")

Retrieving http://py4e-data.dr-chuck.net/json?address=AGH+University+of+Science+and+Technology&key=42
Retrieved 2324 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Academy+of+Fine+Arts+Warsaw+Poland&key=42
Retrieved 2039 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=American+University+in+Cairo&key=42
Retrieved 1773 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Arizona+State+University&key=42
Retrieved 1789 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Athens+Information+Technology&key=42
Retrieved 1996 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=BITS+Pilani&key=42
Retrieved 1822 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Babcock+University&key=42
Retrieved 1847 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Banaras+Hindu+University&key=42
Retrieved 2001 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Bangalore+University&key=42
Retrieved 2226 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Baylor+University&key=42
Retrieved 2104 characters {    "results" : [
Pausing for a bit...

Retrieving http://py4e-data.dr-chuck.net/json?address=Beijing+normal+university&key=42
Retrieved 2223 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Belarusian+State+University&key=42
Retrieved 2210 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Belgrade+University&key=42
Retrieved 1979 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Beloit+College&key=42
Retrieved 2286 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Belorussian+State+University&key=42
Retrieved 2210 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Ben+Gurion+University&key=42
Retrieved 2014 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Bharthidasan+University&key=42
Retrieved 1901 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Boston+University&key=42
Retrieved 1995 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=California+Polytechnic+State+University+of+San+Luis+Obispo&key=42
Retrieved 2147 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=California+State+University+San+Bernardino&key=42
Retrieved 2177 characters {    "results" : [
Pausing for a bit...

Retrieving http://py4e-data.dr-chuck.net/json?address=City+of+Westminster+College&key=42
Retrieved 2136 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Columbia+University&key=42
Retrieved 2006 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Cranfield+University&key=42
Retrieved 2166 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Czech+Technical+University+in+Prague&key=42
Retrieved 1863 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Dartmouth&key=42
Retrieved 2154 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=De+Anza+College&key=42
Retrieved 2156 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Distant+University+of+Hagen&key=42
Retrieved 2312 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Dnipropetrovsk+National+University&key=42
Retrieved 2423 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Dokuz+Eylul+University&key=42
Retrieved 2024 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Drexel&key=42
Retrieved 2334 characters {    "results" : [
Pausing for a bit...

Retrieving http://py4e-data.dr-chuck.net/json?address=Drexel+University+and+University+of+Texas+at+Austin&key=42
Retrieved 4087 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Duke+University&key=42
Retrieved 1793 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=EM+Lyon&key=42
Retrieved 2143 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Ecole+centrale+de+PARIS&key=42
Retrieved 2358 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Elon+University&key=42
Retrieved 1725 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Erhvervsakademi+Sydvest&key=42
Retrieved 1732 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Escuela+Superior+Politecnica+del+Litoral&key=42
Retrieved 1980 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Fachhochschule+Dusseldorf&key=42
Retrieved 2542 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Fachhochschule+FH+Salzburg&key=42
Retrieved 2106 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Faculdade+de+Tecnologia+do+Estado+de+Sao+Paulo&key=42
Retrieved 1784 characters {    "results" : [
Pausing for a bit...

Retrieving http://py4e-data.dr-chuck.net/json?address=Faculty+of+Technical+Sciences+Novi+Sad+Serbia&key=42
Retrieved 2163 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Farmingdale+State+University&key=42
Retrieved 2130 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Federal+University+of+Minas+Gerais&key=42
Retrieved 2286 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Florida+Atlantic+University&key=42
Retrieved 2129 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Franklin+Pierce+College&key=42
Retrieved 2272 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Gauhati+University&key=42
Retrieved 2275 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=George+Mason+University&key=42
Retrieved 2129 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Georgetown+University+Law+Center&key=42
Retrieved 2188 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Georgia+State+University&key=42
Retrieved 1981 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Grandville&key=42
Retrieved 1752 characters {    "results" : [
Pausing for a bit...

Retrieving http://py4e-data.dr-chuck.net/json?address=Groep+T+University&key=42
Retrieved 2158 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Hanoi+University+of+Science+and+Technology&key=42
Retrieved 1864 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Hebrew+University&key=42
Retrieved 1281 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=IIIT+Hyderabad&key=42
Retrieved 2253 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=IIT+KANPUR&key=42
Retrieved 2028 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=IT+College+of+Estonia&key=42
Retrieved 1211 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=IU&key=42
Retrieved 2316 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=IUAV+Venezia&key=42
Retrieved 2327 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Illinois+Institute+of+Technology&key=42
Retrieved 2276 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Illinois+State+University+Joliet+Junior+College&key=42
Retrieved 4489 characters {    "results" : [
Pausing for a bit...

Retrieving http://py4e-data.dr-chuck.net/json?address=Indian+Institute+of+Technology&key=42
Retrieved 1204 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Indian+Institute+of+Technology+Kharagpur+India&key=42
Retrieved 1837 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Indian+School+of+Mines+Dhanbad&key=42
Retrieved 2636 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Indiana+University&key=42
Retrieved 2297 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Indiana+University+at+Bloomington&key=42
Retrieved 2316 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Institut+Superieur+de+technologies&key=42
Retrieved 52 characters {    "results" : [],

Retrieving http://py4e-data.dr-chuck.net/json?address=Institute+of+Business+and+Modern+Technologies&key=42
Retrieved 52 characters {    "results" : [],

Retrieving http://py4e-data.dr-chuck.net/json?address=Instituto+Tecnologico+de+Santo+Domingo&key=42
Retrieved 2458 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=International+Institute+of+Information+Technology+Hyderabad&key=42
Retrieved 2253 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Irkutsk+State+University&key=42
Retrieved 2208 characters {    "results" : [
Pausing for a bit...

Retrieving http://py4e-data.dr-chuck.net/json?address=JADAVPUR+UNIVERSITY&key=42
Retrieved 2461 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Jawaharlal+Nehru+Technological+University&key=42
Retrieved 2469 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Jawaharlal+Nehru+University&key=42
Retrieved 1804 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Jordan+University+of+Science+and+Technology&key=42
Retrieved 1452 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=K-State&key=42
Retrieved 1795 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=KUL&key=42
Retrieved 52 characters {    "results" : [],

Retrieving http://py4e-data.dr-chuck.net/json?address=Kalamazoo+College&key=42
Retrieved 2324 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Kaunas+Technology+University&key=42
Retrieved 1973 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Kaunas+university+of+technology&key=42
Retrieved 1973 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Kazan+Federal+University&key=42
Retrieved 2383 characters {    "results" : [
Pausing for a bit...

Retrieving http://py4e-data.dr-chuck.net/json?address=Kent+State+University&key=42
Retrieved 2115 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Kharkiv+State+Academy+of+Municipal+Economy+Ukraine&key=42
Retrieved 2448 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=King+Mongkuts+University+of+Technology+Thonburi&key=42
Retrieved 2290 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Kokshetau+Institute+of+Economics+and+Management&key=42
Retrieved 1953 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Kyiv+Polytechnic+Institute&key=42
Retrieved 2335 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Kyiv+Polytechnical+Institute&key=42
Retrieved 2335 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Kyiv+Unisersity+of+Oriental+Language&key=42
Retrieved 1699 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Laurentian+University&key=42
Retrieved 2389 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Lisandro+Alvarado&key=42
Retrieved 52 characters {    "results" : [],

Retrieving http://py4e-data.dr-chuck.net/json?address=Lodz+University+of+Technology&key=42
Retrieved 2276 characters {    "results" : [
Pausing for a bit...

Retrieving http://py4e-data.dr-chuck.net/json?address=Lviv+University&key=42
Retrieved 1901 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=MSU&key=42
Retrieved 1503 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Madras+university&key=42
Retrieved 2451 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Magnitogorsk+State+Technical+University&key=42
Retrieved 2239 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Malayer+Azad+University&key=42
Retrieved 1673 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Marietta+College&key=42
Retrieved 2122 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Masdar+Institute&key=42
Retrieved 52 characters {    "results" : [],

Retrieving http://py4e-data.dr-chuck.net/json?address=Matematicki+fakultet+Beograd&key=42
Retrieved 2140 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Michigan+State+University&key=42
Retrieved 1503 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Middle+East+Technical+University&key=42
Retrieved 2341 characters {    "results" : [
Pausing for a bit...

Retrieving http://py4e-data.dr-chuck.net/json?address=Missouri+University+of+Science+and+Technology&key=42
Retrieved 2497 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Monash&key=42
Retrieved 1598 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Monash+University&key=42
Retrieved 2007 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Monash+University+Churchill+Australia&key=42
Retrieved 2139 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Monterrey+Institute+of+Technology+and+Higher+Education&key=42
Retrieved 2221 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Moscow+Engineering-Physics+Institute&key=42
Retrieved 2407 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Moscow+Institute+of+Physics+%26+Technology&key=42
Retrieved 2208 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Moscow+State+University&key=42
Retrieved 2547 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=NIT+ROURKELA&key=42
Retrieved 2292 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=NYU&key=42
Retrieved 2020 characters {    "results" : [
Pausing for a bit...

Retrieving http://py4e-data.dr-chuck.net/json?address=Nagpur+University&key=42
Retrieved 2217 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Nanyang+Technological+University&key=42
Retrieved 1624 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=National+Institute+of+Technology+Jalandhar&key=42
Retrieved 2063 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=National+Taiwan+University&key=42
Retrieved 2212 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=National+University+of+Engineering&key=42
Retrieved 2167 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=North+Central+College&key=42
Retrieved 2520 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Northeastern+University&key=42
Retrieved 2304 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Northwestern+University&key=42
Retrieved 2117 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Obninsk+Technical+University+of+Nuclear+Power+Engineering+Russia&key=42
Retrieved 1868 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Old+Dominion+University&key=42

Retrieved 1931 characters {    "results" : [
Pausing for a bit...

Retrieving http://py4e-data.dr-chuck.net/json?address=Oregon+Institute+of+Technology&key=42
Retrieved 2128 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=PUCMM&key=42
Retrieved 2246 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Payame+Noor+University&key=42
Retrieved 1888 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Penn+State+University&key=42
Retrieved 1793 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Politecnico+di+Milano&key=42
Retrieved 52 characters {    "results" : [],

Retrieving http://py4e-data.dr-chuck.net/json?address=Politehnica+University+Bucharest&key=42
Retrieved 2351 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Polytechnic+University+of+Timisoara&key=42
Retrieved 2157 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Pondicherry+University&key=42
Retrieved 2257 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Pontificia+universidad+catolica+de+chile&key=42
Retrieved 2445 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Portland+State+University&key=42
Retrieved 2464 characters {    "results" : [
Pausing for a bit...

Retrieving http://py4e-data.dr-chuck.net/json?address=Purdue+University+Indianapolis&key=42
Retrieved 2524 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=R+V+College+of+Engineering&key=42
Retrieved 2419 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=RPI&key=42
Retrieved 2092 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Ramapo+College+of+New+Jersey&key=42
Retrieved 2277 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Rochester+Institute+of+Technology&key=42
Retrieved 2482 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=SASTRA+University&key=42
Retrieved 1883 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Saint+Petersburg+State+University&key=42
Retrieved 2226 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Saint+Petersburg+State+University+of+Aerospace+Instrumentation&key=42
Retrieved 2030 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Saint-Petersburg+Polytechnic+Univesity&key=42
Retrieved 2221 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=San+Francisco+State+University&key=42
Retrieved 2327 characters {    "results" : [
Pausing for a bit...

Retrieving http://py4e-data.dr-chuck.net/json?address=San+Jose+State+University&key=42
Retrieved 2304 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Shanghai+Jiao+Tong+University&key=42
Retrieved 1878 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Sharif+University+of+Technology&key=42
Retrieved 1643 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Simon+Bolivar+University&key=42
Retrieved 1671 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Simon+Fraser+University&key=42
Retrieved 2135 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Smolensk+State+University&key=42
Retrieved 2219 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Sonoma+State+University&key=42
Retrieved 2137 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=South+Federal+University&key=42
Retrieved 2443 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Spiru+Haret+University&key=42
Retrieved 2357 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Stanford&key=42
Retrieved 1911 characters {    "results" : [
Pausing for a bit...

Retrieving http://py4e-data.dr-chuck.net/json?address=State+University+of+Campinas&key=42
Retrieved 2116 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=State+University+of+New+York+College+at+Oswego&key=42
Retrieved 1770 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Stellenbosch+University&key=42
Retrieved 1956 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Stonehill+College&key=42
Retrieved 2331 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Tallinn+University&key=42
Retrieved 2164 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Tallinn+University+of+Technology&key=42
Retrieved 2156 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Tampere+University+of+Technology&key=42
Retrieved 1747 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Tanta+University&key=42
Retrieved 2075 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Tarrant+County+College&key=42
Retrieved 2162 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Technical+University+of+Cluj-Napoca&key=42
Retrieved 2161 characters {    "results" : [
Pausing for a bit...

Retrieving http://py4e-data.dr-chuck.net/json?address=Technion&key=42
Retrieved 1784 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Tel+Aviv+University&key=42
Retrieved 1482 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=The+Jerusalem+collage+of+engineering&key=42
Retrieved 2583 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=The+University+of+Latvia&key=42
Retrieved 1979 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=The+University+of+Manchester&key=42
Retrieved 1977 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=The+University+of+South+Africa&key=42
Retrieved 2250 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Transilvania+University&key=42
Retrieved 2315 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Tufts+University&key=42
Retrieved 1940 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=UC+Berkeley&key=42
Retrieved 1725 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=UCLA&key=42
Retrieved 1989 characters {    "results" : [
Pausing for a bit...

Retrieving http://py4e-data.dr-chuck.net/json?address=UCSD&key=42
Retrieved 2286 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=UIUC&key=42
Retrieved 1657 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=UMD&key=42
Retrieved 1836 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=UNISA&key=42
Retrieved 2250 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=UNIVERSIDAD+DE+Buenos+Aires&key=42
Retrieved 2328 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=UOC&key=42
Retrieved 2135 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=USC&key=42
Retrieved 2008 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=UW+Madison&key=42
Retrieved 1653 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Universidad+Central+de+Venezuela&key=42
Retrieved 2044 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Universidad+Complutense+de+Madrid&key=42
Retrieved 2070 characters {    "results" : [
Pausing for a bit...

Retrieving http://py4e-data.dr-chuck.net/json?address=Universidad+Cooperativa+de+Colombia&key=42
Retrieved 52 characters {    "results" : [],

Retrieving http://py4e-data.dr-chuck.net/json?address=Universidad+Nacional+Autonoma+de+Mexico&key=42

Retrieved 2239 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Universidad+Nacional+Costa+Rica&key=42
Retrieved 1686 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Universidad+Nacional+de+Colombia&key=42
Retrieved 1934 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Universidad+Tecnologica+Boliviana&key=42
Retrieved 2220 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Universidad+de+Buenos+Aires&key=42
Retrieved 2328 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Universidad+de+Castilla+La+Mancha&key=42
Retrieved 2139 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Universidad+de+Los+Andes+Colombia&key=42
Retrieved 2316 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Universidad+de+Oriente&key=42
Retrieved 1742 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Universidad+de+San+Carlos+de+Guatemala&key=42
Retrieved 2220 characters {    "results" : [
Pausing for a bit...

Retrieving http://py4e-data.dr-chuck.net/json?address=Universidad+de+Valladolid&key=42
Retrieved 2128 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Universidad+de+la+Sabana&key=42
Retrieved 1598 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Universidad+del+Valle+de+Guatemala&key=42
Retrieved 2072 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Universidade+Federal+da+Paraiba&key=42
Retrieved 1925 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Universidade+Federal+de+Santa+Catarina&key=42
Retrieved 2315 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Universidade+Federal+do+Rio+Grande+do+Sul&key=42
Retrieved 1910 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Universidade+Federal+do+Rio+de+Janeiro&key=42
Retrieved 2410 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Universidade+Tecnica+de+Lisboa&key=42
Retrieved 1589 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Universidade+de+Sao+Paulo&key=42
Retrieved 1710 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Universidade+do+Minho&key=42
Retrieved 1798 characters {    "results" : [
Pausing for a bit...

Retrieving http://py4e-data.dr-chuck.net/json?address=Universitas+Gadjah+Mada&key=42
Retrieved 2332 characters {    "results" : [
Retrieved 200 locations, restart to retrieve more
Run geodump.py to read the data from the database so you can vizualize it on a map.

In [12]:
import sqlite3
import json
import codecs

conn = sqlite3.connect('geodata.sqlite')
cur = conn.cursor()

cur.execute('SELECT * FROM Locations')
fhand = codecs.open('where.js', 'w', "utf-8")
fhand.write("myData = [\n")
count = 0
for row in cur :
    data = str(row[1].decode())
    try: js = json.loads(str(data))
    except: continue

    if not('status' in js and js['status'] == 'OK') : continue

    lat = js["results"][0]["geometry"]["location"]["lat"]
    lng = js["results"][0]["geometry"]["location"]["lng"]
    if lat == 0 or lng == 0 : continue
    where = js['results'][0]['formatted_address']
    where = where.replace("'", "")
    try :
        print(where, lat, lng)

        count = count + 1
        if count > 1 : fhand.write(",\n")
        output = "["+str(lat)+","+str(lng)+", '"+where+"']"
        fhand.write(output)
    except:
        continue

fhand.write("\n];\n")
cur.close()
fhand.close()
print(count, "records written to where.js")
print("Open where.html to view the data in a browser")

aleja Adama Mickiewicza 30, 30-059 Kraków, Poland 50.06688579999999 19.9136192
Krakowskie Przedmieście 5, 00-068 Warszawa, Poland 52.2394019 21.0150792
Admin building AUC قسم أول القاهرة الجديدة، محافظة القاهرة‬ 4728120،، New Cairo 1, Cairo Governorate 4728120, Egypt 30.0201508 31.49908139999999
Tempe, AZ 85281, USA 33.4242399 -111.9280527
Monumental Plaza, Building C, 1st Floor, Leof. Kifisias 44, Marousi 151 25, Greece 38.0399391 23.8030901
Vidya Vihar, Pilani, Rajasthan 333031, India 28.3588163 75.58802039999999
121103, Ilishan-Remo, Ogun State, Nigeria 6.8920758 3.7181452
Ajagara, Varanasi, Uttar Pradesh 221005, India 25.2677203 82.99125819999999
Mysore Rd, Jnana Bharathi, Bengaluru, Karnataka 560056, India 12.9504048 77.5020617
1311 S 5th St, Waco, TX 76706, USA 31.5500848 -97.11354
19 Xin Wai Da Jie, Beitaipingzhuang, Hai Dian Qu, Bei Jing Shi, China, 100875 39.9619537 116.3662615
prasp. Niezaliežnasci 4, Minsk, Belarus 53.8930049 27.545623
Studentski trg 1, Beograd, Serbia 44.8184518 20.4575913
700 College St, Beloit, WI 53511, USA 42.5030333 -89.0309048
prasp. Niezaliežnasci 4, Minsk, Belarus 53.8930049 27.545623
David Ben Gurion Blvd 1, Beer Sheva, Israel 31.261426 34.7995546
Palkalaiperur, Tiruchirappalli, Tamil Nadu 620024, India 10.6779085 78.74454879999999
Boston, MA 02215, USA 42.3504997 -71.1053991
1 Grand Ave, San Luis Obispo, CA 93407, USA 35.3050053 -120.6624942
5500 University Pkwy, San Bernardino, CA 92407, USA 34.1813584 -117.3231875
25 Paddington Grn, London W2 1NB, UK 51.5210416 -0.1746649
New York, NY 10027, USA 40.8075355 -73.9625727
College Rd, Cranfield, Wharley End, Bedford MK43 0AL, UK 52.0740377 -0.6282057
166 36 Prague 6, Czechia 50.1030364 14.3912841
Hanover, NH 03755, USA 43.7044406 -72.2886934
21250 Stevens Creek Blvd, Cupertino, CA 95014, USA 37.3192806 -122.0447919
Universitätsstraße 11, 58097 Hagen, Germany 51.3769424 7.4946354
Haharina Ave, 72, Dnipro, Dnipropetrovska oblast, Ukraine, 49000 48.4331922 35.0427966
No: 144 35210, Alsancak, Cumhuriyet Blv, 35220 Konak/İzmir, Turkey 38.430691 27.13692
3141 Chestnut St, Philadelphia, PA 19104, USA 39.9566127 -75.18994409999999
Austin, TX 78712, USA 30.2849185 -97.7340567
Durham, NC 27708, USA 36.0014258 -78.9382286
23 Av. Guy de Collongue, 69130 Écully, France 45.7864448 4.7641329
CentraleSupélec, 3 Rue Joliot Curie, 91190 Gif-sur-Yvette, France 48.709445 2.1661629
Elon, NC, USA 36.1007437 -79.5066375
Alsion 4, 6400 Sønderborg, Denmark 54.9134537 9.7780195
Vía Perimetral 5, Guayaquil, Ecuador -2.1478802 -79.9645694
Münsterstraße 156, 40476 Düsseldorf, Germany 51.24683899999999 6.7916647
Urstein S 1, 5412 Salzburg, Austria 47.7233835 13.0871253
São Paulo, State of São Paulo, Brazil -23.5557714 -46.6395571
Trg Dositeja Obradovića 6, Novi Sad 106314, Serbia 45.2461012 19.8516968
2350 NY-110, Farmingdale, NY 11735, USA 40.7529167 -73.4266988
Av. Pres. Antônio Carlos, 6627 - Pampulha, Belo Horizonte - MG, 31270-901, Brazil -19.870682 -43.9677359
777 Glades Rd, Boca Raton, FL 33431, USA 26.3749876 -80.10106329999999
40 University Dr, Rindge, NH 03461, USA 42.7789743 -72.05553929999999
Gopinath Bordoloi Nagar, Jalukbari, Guwahati, Assam 781014, India 26.1540389 91.66296679999999
4400 University Dr, Fairfax, VA 22030, USA 38.8314578 -77.31174709999999
600 New Jersey Ave NW, Washington, DC 20001, USA 38.8977953 -77.0129087
Atlanta, GA 30302, USA 33.753068 -84.38528190000001
Grandville, MI, USA 42.9097484 -85.7630885
Andreas Vesaliusstraat 13, 3000 Leuven, Belgium 50.87485419999999 4.7077677
58 P. Lê Thanh Nghị, Bách Khoa, Hai Bà Trưng, Hà Nội, Vietnam 21.0036886 105.8488735
Jerusalem 31.7945578 35.2414009
Professor CR Rao Rd, Gachibowli, Hyderabad, Telangana 500032, India 17.4448649 78.34981379999999
Kalyanpur, Kanpur, Uttar Pradesh 208016, India 26.5123388 80.2329
Estonia 58.595272 25.013607
107 S Indiana Ave, Bloomington, IN 47405, USA 39.1682449 -86.52300729999999
Santa Croce, 191, 30135 Venezia VE, Italy 45.4377574 12.3223297
10 W 35th St, Chicago, IL 60616, USA 41.8348731 -87.6270059
Jr College, Joliet, IL 60431, USA 41.5042613 -88.17752689999999
India 20.593684 78.96288
Kharagpur, West Bengal 721302, India 22.3149274 87.31053109999999
Police Line Road, Main Campus IIT (ISM, near Rani Bandh, IIT (ISM, Hirapur, Sardar Patel Nagar, Dhanbad, Jharkhand 826004, India 23.8142953 86.44118069999999
107 S Indiana Ave, Bloomington, IN 47405, USA 39.1784384 -86.5133166
107 S Indiana Ave, Bloomington, IN 47405, USA 39.1682449 -86.52300729999999
Av. de los Próceres 49, Santo Domingo 10602, Dominican Republic 18.4880037 -69.96249499999999
Professor CR Rao Rd, Gachibowli, Hyderabad, Telangana 500032, India 17.4448649 78.34981379999999
Ulitsa Karla Marksa, 1, Irkutsk, Irkutskaya oblast, Russia, 664003 52.2766643 104.2777445
188, Raja Subodh Chandra Mallick Rd, Jadavpur, Kolkata, West Bengal 700032, India 22.4988822 88.3714123
F9VR+8H2, Ashok Nagar, Kukatpally Housing Board Colony, Kukatpally, Hyderabad, Telangana 500085, India 17.4932682 78.3913929
New Mehrauli Road, JNU Ring Rd, New Delhi, Delhi 110067, India 28.5398035 77.1664047
3030, الرمثا، Jordan 32.4950392 35.9912257
Manhattan, KS 66506, USA 39.1974437 -96.5847249
1200 Academy St, Kalamazoo, MI 49006, USA 42.290035 -85.598145
K. Donelaičio g. 73, 44249 Kaunas, Lithuania 54.898991 23.912825
K. Donelaičio g. 73, 44249 Kaunas, Lithuania 54.898991 23.912825
ulitsa Kremlevskaya, 18, Kazan, Respublika Tatarstan, Russia, 420008 55.790447 49.1214348
800 E Summit St, Kent, OH 44240, USA 41.1497945 -81.34331590000001
Marshala Bazhanova St, 17, Kharkiv, Kharkivska oblast, Ukraine, 61002 49.9953019 36.2412463
126 Thanon Pracha Uthit, Khwaeng Bang Mot, Khet Thung Khru, Krung Thep Maha Nakhon 10140, Thailand 13.6512522 100.4964428
Kokshetau 020000, Kazakhstan 53.2871307 69.40444939999999
Peremohy Ave, 37, Kyiv, Ukraine, 03056 50.4488974 30.456977
Peremohy Ave, 37, Kyiv, Ukraine, 03056 50.4488974 30.456977
Kyiv, Ukraine, 02000 50.4501 30.5234
935 Ramsey Lake Rd, Sudbury, ON P3E 2C6, Canada 46.4672485 -80.9757296
Stefana Żeromskiego 116, 90-924 Łódź, Poland 51.7537146 19.4517176
Lviv, Lviv Oblast, Ukraine, 79000 49.839683 24.029717
Michigan, USA 42.701848 -84.4821719
Navalar Nagar, Chepauk, Triplicane, Chennai, Tamil Nadu 600005, India 13.0660293 80.28317190000001
Lenin Ave, 38, Magnitogorsk, Chelyabinskaya oblast, Russia, 455000 53.42119599999999 58.98193999999999
Hamadan Province, Malayer, جاده سلامت، 8R7H+5CM, Iran 34.3129573 48.8285422
215 5th St, Marietta, OH 45750, USA 39.4164811 -81.4498947
Studentski trg 16, Beograd 105104, Serbia 44.8199188 20.4587075
Michigan, USA 42.701848 -84.4821719
Üniversiteler, Dumlupınar Blv. 1/6 D:133, 06800 Çankaya/Ankara, Turkey 39.88983820000001 32.780086
106, Parker Hall, 300 W 13th St, Rolla, MO 65409, USA 37.9537078 -91.7756271
City of Monash, VIC, Australia -37.9015913 145.1155133
Wellington Rd, Clayton VIC 3800, Australia -37.9142416 145.1346592
1 Northways Rd, Churchill VIC 3842, Australia -38.3090975 146.4255391
Av. Eugenio Garza Sada 2501 Sur, Tecnológico, 64849 Monterrey, N.L., Mexico 25.6515649 -100.28954
Kashira Hwy, 31, Moskva, Russia, 115409 55.6502051 37.6643098
Institutskiy Pereulok, 9, Dolgoprudny, Moskovskaya oblast, Russia, 141701 55.9297243 37.5199434
ul. Leninskiye Gory, 1, Moskva, Russia, 119991 55.70393490000001 37.5286695
7W32+69H, National Institute of Technology, Sector 1, Rourkela, Odisha 769008, India 22.2530656 84.9009808
New York, NY 10012, USA 40.72951339999999 -73.9964609
42XQ+4RW, Amravati Rd, Gokulpeth, Nagpur, Maharashtra 440033, India 21.1478747 79.03957199999999
50 Nanyang Ave, Singapore 639798 1.3483099 103.6831347
Grand Trunk Road, Barnala - Amritsar Bypass Rd, Jalandhar, Punjab 144011, India 31.3958746 75.5358439
No. 1, Section 4, Roosevelt Rd, Da’an District, Taipei City, Taiwan 10617 25.0173405 121.5397518
Av. Túpac Amaru 210, Rímac 15333, Peru -12.0238022 -77.04840589999999
30 N Brainard St, Naperville, IL 60540, USA 41.772663 -88.1440142
360 Huntington Ave, Boston, MA 02115, USA 42.3398067 -71.0891717
633 Clark St, Evanston, IL 60208, USA 42.0564594 -87.67526699999999
Obninsk, Kaluga Oblast, Russia, 249034 55.13719099999999 36.607059
5115 Terminal Blvd, Norfolk, VA 23529, USA 36.8853052 -76.3058746
3201 Campus Dr, Klamath Falls, OR 97601, USA 42.2573474 -121.7849109
Autopista Duarte Km 1 1/2, Santiago De Los Caballeros 51000, Dominican Republic 19.4436005 -70.6843785
Tehran Province, Tehran, اتوبان ارتش کوی نفت, Nakhl St, RG23+F4X, Iran 35.8012314 51.5028533
State College, PA 16801, USA 40.7982133 -77.8599084
Splaiul Independenței 313, București 060042, Romania 44.4386064 26.0494925
Piața Victoriei 2, Timișoara 300006, Romania 45.7536393 21.2251614
Pondicherry University, Chinna Kalapet, Kalapet, Puducherry 605014, India 12.0182619 79.8568461
Av. Libertador Bernardo OHiggins 340, 8331150 Santiago, Región Metropolitana, Chile -33.44180680000001 -70.6399544
1825 SW Broadway, Portland, OR 97201, USA 45.5111153 -122.6833385
420 University Blvd, Indianapolis, IN 46202, USA 39.7749927 -86.1772798
Mysore Rd, RV Vidyaniketan, Post, Bengaluru, Karnataka 560059, India 12.9237228 77.4987012
110 8th St, Troy, NY 12180, USA 42.7297628 -73.67888839999999
505 Ramapo Valley Rd, Mahwah, NJ 07430, USA 41.0815852 -74.17610150000002
1 Lomb Memorial Dr, Rochester, NY 14623, USA 43.08484869999999 -77.67153549999999
Trichy-Tanjore Road, Thirumalaisamudram, Thanjavur, Tamil Nadu 613401, India 10.7285131 79.0184111
University Embankment, 7/9, Sankt-Peterburg, Russia, 199034 59.941894 30.2989198
Bolshaya Morskaya Ulitsa, 67, Sankt-Peterburg, Russia, 190000 59.929491 30.296608
Politekhnicheskaya Ulitsa, 29, Sankt-Peterburg, Russia, 195251 60.0076235 30.3731954
1600 Holloway Ave, San Francisco, CA 94132, USA 37.7241492 -122.4799405
1 Washington Sq, San Jose, CA 95192, USA 37.3351874 -121.8810715
China, Shang Hai Shi, Min Hang Qu, 老闵行东川路 邮政编码: 200240 31.0252201 121.4337784
Tehran, Azadi Ave, P932+FM4, Iran 35.7036491 51.3517033
Sartenejas, Caracas, Miranda, Venezuela 10.408363 -66.8755735
8888 University Dr, Burnaby, BC V5A 1S6, Canada 49.2780937 -122.9198833
Ulitsa Przhevalskogo, 4, Smolensk, Smolenskaya oblast, Russia, 214000 54.7845032 32.0452469
1801 E Cotati Ave, Rohnert Park, CA 94928, USA 38.3409222 -122.6730677
ул, Bolshaya Sadovaya Ulitsa, 105/42, Rostov, Rostovskaya oblast, Russia, 344006 47.224719 39.7283339
Strada Ion Ghica 13, București 030045, Romania 44.4332856 26.100986
450 Serra Mall, Stanford, CA 94305, USA 37.4274745 -122.169719
Cidade Universitária Zeferino Vaz - Barão Geraldo, Campinas - SP, 13083-970, Brazil -22.8184393 -47.0647206
Oswego, NY, USA 43.4553461 -76.5104973
Stellenbosch Central, Stellenbosch, South Africa -33.9328078 18.864447
320 Washington St, North Easton, MA 02357, USA 42.05810530000001 -71.08091300000001
Narva mnt 25, 10120 Tallinn, Estonia 59.4387321 24.7713836
Ehitajate tee 5, 12616 Tallinn, Estonia 59.39501839999999 24.6717087
Kalevantie 4, 33100 Tampere, Finland 61.49410729999999 23.7792354
QXRX+XMC, El-Gaish, Tanta Qism 2, Tanta, Gharbia Governorate 6632110, Egypt 30.7924391 30.9991409
300 Trinity Campus Cir, Fort Worth, TX 76102, USA 32.7561692 -97.3381909
Strada Memorandumului 28, Cluj-Napoca 400114, Romania 46.7692463 23.5857078
Haifa, 3200003, Israel 32.7767783 35.0231271
Tel Aviv-Yafo, Israel 32.1133141 34.8043877
Main Block, Velachery Rd, Narayanapuram, Pallikaranai, Chennai, Tamil Nadu 600100, India 12.9456381 80.2077491
Raiņa bulvāris 19, Centra rajons, Rīga, LV-1586, Latvia 56.95080979999999 24.1163132
Oxford Rd, Manchester M13 9PL, UK 53.4668498 -2.2338837
Preller St, Muckleneuk, Pretoria, 0002, South Africa -25.7676604 28.1992624
300 N Broadway, Lexington, KY 40508, USA 38.0516801 -84.49334189999999
419 Boston Ave, Medford, MA 02155, USA 42.4085371 -71.1182729
Berkeley, CA, USA 37.8718992 -122.2585399
Los Angeles, CA 90095, USA 34.068921 -118.4451811
9500 Gilman Dr, La Jolla, CA 92093, USA 32.8800604 -117.2340135
Champaign, IL, USA 40.1019523 -88.2271615
College Park, MD 20742, USA 38.9869183 -76.9425543
Preller St, Muckleneuk, Pretoria, 0002, South Africa -25.7676604 28.1992624
Viamonte 430, C1053 CABA, Argentina -34.5998875 -58.37306949999999
Rambla del Poblenou, 156, 08018 Barcelona, Spain 41.4065636 2.1945816
Los Angeles, CA 90007, USA 34.0223519 -118.285117
Madison, WI, USA 43.076592 -89.4124875
Facultad de Ciencias, Sierra Maestra, Caracas 1040, Distrito Capital, Venezuela 10.4899673 -66.8913397
Av. Séneca, 2, 28040 Madrid, Spain 40.4454368 -3.7299424
Av. Universidad 3004, Copilco Universidad, Coyoacán, 04510 Ciudad de México, CDMX, Mexico 19.3365296 -99.1886248
Avenida 1, Calle 9 Heredia 86 Heredia, Heredia, 40101, Costa Rica 9.9987964 -84.11147489999999
Cra 45, Bogotá, Colombia 4.6381938 -74.08404639999999
C. Colombia 154, La Paz, Bolivia -16.5005605 -68.1342962
Viamonte 430, C1053 CABA, Argentina -34.5998875 -58.37306949999999
Rectorado UCLM, C. Altagracia, 50, 13001 Ciudad Real, Spain 38.9934998 -3.9254365
Cra. 1 #18a-12, La Candelaria, Bogotá, Cundinamarca, Colombia 4.601458099999999 -74.0661334
25VM+C34, Santiago de Cuba, Cuba 20.0435146 -75.81728939999999
HCPW+WMC, 11 Avenida, Cdad. de Guatemala 01012, Guatemala 14.5873005 -90.55336129999999
C/Plaza de Santa Cruz, 8, 47002 Valladolid, Spain 41.6569271 -4.7140547
Chía, Cundinamarca, Colombia 4.855814899999999 -74.0417628
18 Avenida 11-95 Guatemala, Cdad. de Guatemala 01015, Guatemala 14.603762 -90.48924799999999
Campus I Lot. Cidade Universitaria - Castelo Branco, João Pessoa - PB, 58051-900, Brazil -7.137748500000001 -34.8458974
R. Eng. Agronômico Andrei Cristian Ferreira, s/n - Trindade, Florianópolis - SC, 88040-900, Brazil -27.5999666 -48.5194152
Farroupilha, Porto Alegre - RS, 90040-040, Brazil -30.0339726 -51.2190483
Av. Pedro Calmon, 550 - Cidade Universitária da Universidade Federal do Rio de Janeiro, Rio de Janeiro - RJ, 21941-901, Brazil -22.8625345 -43.2234737
Lisbon, Portugal 38.7222524 -9.1393366
Butanta, São Paulo - State of São Paulo, Brazil -23.5613991 -46.7307891
R. da Universidade, 4710-057 Braga, Portugal 41.5607319 -8.3962368
Bulaksumur, Caturtunggal, Kec. Depok, Kabupaten Sleman, Daerah Istimewa Yogyakarta 55281, Indonesia -7.7713847 110.3774998
194 records written to where.js
Open where.html to view the data in a browser